//! Runtime support for code generated by `protoview-build`.
//!
//! Generated view types read a byte buffer in place: [`Scanner`] performs the
//! structural walk that validates a message and locates its fields, and the readers in
//! [`varint`] and [`wire`] pull individual values back out at the offsets that walk
//! recorded, with [`repeated`] re-walking the span of a repeated field. Nothing here
//! allocates, and the crate has no dependencies.
//!
//! Application code does not normally call into this crate directly.

#![cfg_attr(not(test), no_std)]

pub mod error;
pub mod map;
pub mod repeated;
pub mod varint;
pub mod wire;

pub use error::{DecodeError, MAX_DEPTH, MAX_MESSAGE_LEN};
pub use wire::{Field, Scanner, WireType};

#[cfg(test)]
mod tests;
